appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dUMutpOt4QApC/LeoqEw3KI9Up7VZ22cVEj2D/dXvwpWRvN/NbhDI/Wm7aglt87LfUs4+ZnrjRYkr8CkSYPGJLD4GdUUlaSpvxYIYcJoSBsEZD0LrH9b2+ePZMNmETtKemq7Dg8NE2qnAmxMSMs+cTJ1Qvej4MvpqXJ3kXC5Uv7yzadj+sXKJY6C7t6tuJdvq4Fz1hW99XCF6k5yOr/ERDUh/+OIrYAU2cvSD8ag19XkjveYEvBVnxOIpRvfmW2UglnV5f5P7OQ3Qnfsd4ZHVK+nJL7Pd1cogUTD1qy0CqYAbLTCknRQ3RGYqG4IkfCNVdY7zezABWWtSjPTaTPyYaVMDmgn9pzLlfLLXrEYBif7XLuIVuF97uHeVnqnZNV6E17FM0vSIg2MdJNBKPjrtHKv355B0/VArzKkyTs86DNI6rpNu0UiQcsyyEKYGb5SaATwNm7em9OCbzxh1csa2ZIbri5eEMLmHB0xRzStlwApqgBmJExsTt0WKKrU+vc9gZig//Nz64Ya/QpxkWaSBBcZ4EQnxSOagjqT1oFbgt6BLcKM9Jajj40lK6LAuBzn5rd9C67FrKQnt9vTTNkXamvmnWe4ZJVKPDLjLf9LIz0jdwrHst/BM2XXEsOFLVxMv4VZhtgN5T7G/awbEew4oKKJee+gBBHoLriEZKreVC8=}
